import type { RoleContract } from "../shared/contracts.js";

export const ROLE_CONTRACT_VERSION = "2026-08-17.8";

const COORDINATION_TOOLS = [
  "get_goal_context",
  "list_agents",
  "workspace_list",
  "workspace_read",
  "workspace_search",
  "send_agent_message",
  "create_child_goal",
  "start_child_agent",
  "request_verification",
  "submit_evidence",
  "request_approval",
] as const;

const READ_ONLY_TOOLS = [
  "get_goal_context",
  "list_agents",
  "workspace_list",
  "workspace_read",
  "workspace_search",
  "send_agent_message",
  "submit_evidence",
  "request_approval",
] as const;

const BUILDER_TOOLS = [
  ...READ_ONLY_TOOLS,
  "list_checks",
  "workspace_write",
  "apply_patch",
  "run_check",
  "submit_candidate",
] as const;

const VERIFIER_TOOLS = [
  "get_goal_context",
  "list_agents",
  "workspace_list",
  "workspace_read",
  "workspace_search",
  "list_checks",
  "run_check",
  "send_agent_message",
  "record_release_gate",
  "submit_evidence",
] as const;

function director(
  roleId: string,
  displayName: string,
  mission: string,
  modelRouteId: string,
  prohibited: readonly string[],
  requiredChecks: readonly string[],
): RoleContract {
  return {
    roleId,
    displayName,
    kind: "director",
    reportsToRoleId: "ROLE-ORCHESTRATOR",
    mission,
    owns: [mission],
    inputs: ["authorized goal", "scope", "acceptance criteria", "authority", "dependencies", "evidence"],
    outputs: ["bounded decision", "delegated goal", "verification request", "limitations"],
    mayDelegateTo: ["registered descendant roles"],
    mayWriteTo: ["controller goals", "controller messages", "approval requests"],
    approvalRequired: ["external effect", "binding commitment", "scope expansion"],
    definitionOfDone: ["bounded result returned", "limitations recorded", "required checks identified"],
    evaluationSuite: requiredChecks,
    allowedTools: COORDINATION_TOOLS,
    dataAccess: ["public", "internal", "confidential"],
    writeScope: "none",
    mayDelegate: true,
    mayApprove: [],
    prohibited,
    requiredChecks,
    handoffRequirements: ["goal", "scope", "acceptance criteria", "authority", "dependencies", "evidence"],
    completionCriteria: ["bounded result returned", "limitations recorded", "required checks identified"],
    escalationConditions: ["authority missing", "policy conflict", "external effect", "critical risk"],
    modelRouteId,
    independentFromRoleIds: [],
  };
}

function specialist(
  roleId: string,
  displayName: string,
  reportsToRoleId: string,
  mission: string,
  modelRouteId: string,
  writeScope: RoleContract["writeScope"] = "none",
): RoleContract {
  return {
    roleId,
    displayName,
    kind: "specialist",
    reportsToRoleId,
    mission,
    owns: [mission],
    inputs: ["assigned goal", "acceptance criteria", "authorized data", "registered checks"],
    outputs: ["bounded result", "evidence", "limitations", "unresolved decisions"],
    mayDelegateTo: [],
    mayWriteTo:
      writeScope === "isolated"
        ? ["assigned leased workspace", "controller evidence"]
        : ["controller evidence"],
    approvalRequired: ["external effect", "binding commitment", "scope expansion"],
    definitionOfDone: ["acceptance criteria addressed", "evidence submitted", "no hidden external effect"],
    evaluationSuite:
      writeScope === "isolated" ? ["contract checks", "changed-scope checks"] : ["source evidence"],
    allowedTools: writeScope === "isolated" ? BUILDER_TOOLS : READ_ONLY_TOOLS,
    dataAccess: ["public", "internal", "confidential"],
    writeScope,
    mayDelegate: false,
    mayApprove: [],
    prohibited: [
      "self-approval",
      "production deployment",
      "remote push",
      "money movement",
      "owner impersonation",
      "direct owner mailbox access",
    ],
    requiredChecks:
      writeScope === "isolated" ? ["contract checks", "changed-scope checks"] : ["source evidence"],
    handoffRequirements: ["result", "evidence", "limitations", "unresolved decisions"],
    completionCriteria: ["acceptance criteria addressed", "evidence submitted", "no hidden external effect"],
    escalationConditions: ["scope conflict", "approval required", "blocked dependency", "unsafe request"],
    modelRouteId,
    independentFromRoleIds: [],
  };
}

function verifier(
  roleId: string,
  displayName: string,
  mission: string,
  modelRouteId: string,
  independentFromRoleIds: readonly string[],
): RoleContract {
  return {
    roleId,
    displayName,
    kind: "verifier",
    reportsToRoleId: "ROLE-ORCHESTRATOR",
    mission,
    owns: [mission],
    inputs: ["exact subject identity", "acceptance criteria", "registered checks", "candidate evidence"],
    outputs: ["pass, fail, or unverified finding", "limitations", "release gate result"],
    mayDelegateTo: [],
    mayWriteTo: ["controller evidence", "release gate ledger"],
    approvalRequired: ["release", "deployment", "adoption"],
    definitionOfDone: [
      "pass, fail, or unverified recorded",
      "limitations recorded",
      "candidate identity unchanged",
    ],
    evaluationSuite: ["independent reproduction", "candidate identity match", "limitation review"],
    allowedTools: VERIFIER_TOOLS,
    dataAccess: ["public", "internal", "confidential", "privileged"],
    writeScope: "none",
    mayDelegate: false,
    mayApprove: ["evidence_acceptance"],
    prohibited: [
      "candidate modification",
      "self-certification",
      "production deployment",
      "remote push",
      "approval of own evidence",
    ],
    requiredChecks: ["independent reproduction", "candidate identity match", "limitation review"],
    handoffRequirements: ["candidate identity", "scope", "acceptance criteria", "reproduction procedure"],
    completionCriteria: [
      "pass, fail, or unverified recorded",
      "limitations recorded",
      "candidate identity unchanged",
    ],
    escalationConditions: ["candidate mutation", "missing evidence", "critical finding", "scope ambiguity"],
    modelRouteId,
    independentFromRoleIds,
  };
}

const roleContracts: RoleContract[] = [
  {
    roleId: "ROLE-OWNER",
    displayName: "Human Owner",
    kind: "human",
    reportsToRoleId: null,
    mission: "Set company goals, authority, budget, permissions, and exact consequential approvals.",
    owns: ["company goals", "authority boundaries", "budgets", "consequential approvals"],
    inputs: ["verified evidence", "approval request", "risk and limitations"],
    outputs: ["authorized goal", "exact approval decision", "recorded rejection or rollback"],
    mayDelegateTo: ["ROLE-ORCHESTRATOR"],
    mayWriteTo: ["controller goals", "approval ledger", "improvement review ledger"],
    approvalRequired: [],
    definitionOfDone: ["owner decision recorded"],
    evaluationSuite: [],
    allowedTools: [],
    dataAccess: ["public", "internal", "confidential", "privileged"],
    writeScope: "external",
    mayDelegate: true,
    mayApprove: ["goal", "release", "deployment", "email", "legal_commitment", "money_movement"],
    prohibited: [],
    requiredChecks: [],
    handoffRequirements: ["authorized goal", "authority limits", "approval conditions"],
    completionCriteria: ["owner decision recorded"],
    escalationConditions: [],
    modelRouteId: null,
    independentFromRoleIds: [],
  },
  {
    roleId: "ROLE-ORCHESTRATOR",
    displayName: "Chief Orchestrator",
    kind: "orchestrator",
    reportsToRoleId: "ROLE-OWNER",
    mission: "Translate one owner-authorized goal into bounded work and reconcile verified results.",
    owns: ["goal decomposition", "role assignment", "cross-department reconciliation"],
    inputs: ["owner-authorized goal", "authority", "scope", "acceptance criteria", "dependencies"],
    outputs: ["bounded child goals", "reconciled evidence", "owner decision queue"],
    mayDelegateTo: ["registered descendant roles"],
    mayWriteTo: ["controller goals", "controller messages", "approval requests"],
    approvalRequired: ["external effect", "critical scope change", "consequential commitment"],
    definitionOfDone: [
      "all child results reconciled",
      "independent evidence accepted",
      "owner decisions surfaced",
    ],
    evaluationSuite: ["scope completeness", "role separation", "evidence completeness"],
    allowedTools: COORDINATION_TOOLS,
    dataAccess: ["public", "internal", "confidential"],
    writeScope: "none",
    mayDelegate: true,
    mayApprove: [],
    prohibited: [
      "self-approval",
      "production deployment",
      "email sending",
      "money movement",
      "legal commitment",
    ],
    requiredChecks: ["scope completeness", "role separation", "evidence completeness"],
    handoffRequirements: [
      "goal",
      "authority",
      "role",
      "scope",
      "acceptance criteria",
      "dependencies",
      "checks",
    ],
    completionCriteria: [
      "all child results reconciled",
      "independent evidence accepted",
      "owner decisions surfaced",
    ],
    escalationConditions: ["goal conflict", "missing owner authority", "critical risk", "external effect"],
    modelRouteId: "route-critical-orchestration",
    independentFromRoleIds: [],
  },
  director(
    "ROLE-COMMS-DIRECTOR",
    "Communications Director",
    "Own company communications intake, classification, drafting, and escalation without autonomous sending.",
    "route-routine-director",
    ["autonomous email sending", "direct owner mailbox access", "binding commitment", "owner impersonation"],
    ["recipient provenance", "draft policy review"],
  ),
  director(
    "ROLE-BILLING-DIRECTOR",
    "Billing Director",
    "Own invoice, payment, reconciliation, collection, and adjustment evidence without moving money.",
    "route-complex-director",
    ["money movement", "refund execution", "price change", "unverified paid status"],
    ["ledger reconciliation", "transaction provenance"],
  ),
  director(
    "ROLE-LEGAL-DIRECTOR",
    "Legal Operations Director",
    "Coordinate legal intake, deadlines, research, and counsel handoffs without acting as counsel.",
    "route-critical-director",
    ["legal advice", "signature", "acceptance", "binding commitment", "court filing"],
    ["jurisdiction and deadline review", "qualified-counsel boundary"],
  ),
  director(
    "ROLE-PRODUCT-DIRECTOR",
    "Product Director",
    "Translate owner goals and business evidence into prioritized, testable product outcomes.",
    "route-complex-director",
    ["production deployment", "implementation self-approval", "unapproved scope expansion"],
    ["acceptance criteria", "customer-value evidence"],
  ),
  director(
    "ROLE-TECH-DIRECTOR",
    "Technology Director",
    "Coordinate implementation specialists and return immutable candidates with implementation evidence.",
    "route-complex-director",
    ["production deployment", "remote push", "self-approval", "shared working-tree edits"],
    ["changed-scope checks", "candidate identity"],
  ),
  verifier(
    "ROLE-SECURITY-DIRECTOR",
    "Security Director",
    "Independently challenge authorization, isolation, secrets, untrusted input, and release safety.",
    "route-critical-review",
    [
      "ROLE-TECH-DIRECTOR",
      "ROLE-DESIGN",
      "ROLE-BACKEND",
      "ROLE-WEB",
      "ROLE-MOBILE",
      "ROLE-INTEGRATIONS",
      "ROLE-VOICE",
      "ROLE-DEPLOYMENT",
      "ROLE-OPERATIONS",
      "ROLE-EXPERIMENTER",
    ],
  ),
  verifier(
    "ROLE-QUALITY-DIRECTOR",
    "Quality Director",
    "Independently verify observable behavior against acceptance criteria and candidate identity.",
    "route-critical-review",
    [
      "ROLE-ORCHESTRATOR",
      "ROLE-TECH-DIRECTOR",
      "ROLE-DESIGN",
      "ROLE-BACKEND",
      "ROLE-WEB",
      "ROLE-MOBILE",
      "ROLE-INTEGRATIONS",
      "ROLE-VOICE",
      "ROLE-DEPLOYMENT",
      "ROLE-OPERATIONS",
      "ROLE-EXPERIMENTER",
    ],
  ),
  director(
    "ROLE-IMPROVEMENT-DIRECTOR",
    "Improvement Director",
    "Convert recurring sanitized evidence into bounded hypotheses, experiments, and reversible proposals.",
    "route-complex-director",
    ["self-adoption", "production experiment", "approval weakening", "raw private transcript retention"],
    ["baseline", "safety metric", "comparative result"],
  ),
  specialist(
    "ROLE-TRIAGE",
    "Triage & Routing Specialist",
    "ROLE-COMMS-DIRECTOR",
    "Classify proven recipient mail and route it without changing content.",
    "route-routine-specialist",
  ),
  specialist(
    "ROLE-GENERAL-COMMS",
    "General Communications Specialist",
    "ROLE-COMMS-DIRECTOR",
    "Prepare bounded, policy-compliant communication drafts.",
    "route-routine-specialist",
  ),
  specialist(
    "ROLE-CONTACT",
    "Contact & Follow-up Specialist",
    "ROLE-COMMS-DIRECTOR",
    "Track approved contacts, follow-up obligations, and response evidence.",
    "route-routine-specialist",
  ),
  specialist(
    "ROLE-SCHEDULING",
    "Scheduling Specialist",
    "ROLE-COMMS-DIRECTOR",
    "Prepare scheduling options without booking external calendars.",
    "route-routine-specialist",
  ),
  specialist(
    "ROLE-COMPLAINTS",
    "Complaints & Escalation Specialist",
    "ROLE-COMMS-DIRECTOR",
    "Classify complaints, preserve exact evidence, and escalate reputation or safety risk.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-INVOICE",
    "Invoice Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Prepare and reconcile bounded invoice records.",
    "route-routine-specialist",
  ),
  specialist(
    "ROLE-PAYMENT",
    "Payment Tracking Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Compare internal and provider payment evidence without marking paid from claims alone.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-RECONCILIATION",
    "Reconciliation Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Reconcile ledger and provider records and surface discrepancies.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-COLLECTIONS",
    "Collections Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Prepare policy-bounded collection recommendations without customer contact.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-ADJUSTMENTS",
    "Adjustments & Disputes Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Analyze adjustments and disputes without moving money.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-PAYABLES",
    "Payables & Reporting Specialist",
    "ROLE-BILLING-DIRECTOR",
    "Prepare payable and reporting evidence without payment authority.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-LEGAL-INTAKE",
    "Legal Intake Specialist",
    "ROLE-LEGAL-DIRECTOR",
    "Preserve legal requests, deadlines, and exact source language.",
    "route-complex-specialist",
  ),
  specialist(
    "ROLE-CONTRACTS",
    "Contract Specialist",
    "ROLE-LEGAL-DIRECTOR",
    "Analyze contract text and prepare issues for qualified review without acceptance.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-COMPLIANCE",
    "Compliance & Privacy Specialist",
    "ROLE-LEGAL-DIRECTOR",
    "Assess compliance and privacy requirements and surface owner or counsel decisions.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-IP",
    "Corporate & IP Specialist",
    "ROLE-LEGAL-DIRECTOR",
    "Research naming, corporate, and intellectual-property evidence without claiming clearance.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-COUNSEL",
    "Disputes & Counsel Coordinator",
    "ROLE-LEGAL-DIRECTOR",
    "Prepare counsel handoffs, deadlines, and evidence without legal representation.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-DESIGN",
    "Product & UX Specialist",
    "ROLE-PRODUCT-DIRECTOR",
    "Define approved interaction contracts and observable acceptance criteria.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-BACKEND",
    "Backend Specialist",
    "ROLE-TECH-DIRECTOR",
    "Implement server behavior only within an isolated leased workspace.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-WEB",
    "Frontend Specialist",
    "ROLE-TECH-DIRECTOR",
    "Implement browser behavior only within an isolated leased workspace.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-MOBILE",
    "Mobile Specialist",
    "ROLE-TECH-DIRECTOR",
    "Implement approved mobile behavior in an isolated leased workspace.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-INTEGRATIONS",
    "Integrations Specialist",
    "ROLE-TECH-DIRECTOR",
    "Implement versioned integration boundaries without enabling production providers.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-VOICE",
    "Voice Specialist",
    "ROLE-TECH-DIRECTOR",
    "Implement bounded voice interfaces without activating production telephony.",
    "route-complex-specialist",
    "isolated",
  ),
  specialist(
    "ROLE-DEPLOYMENT",
    "Deployment Specialist",
    "ROLE-TECH-DIRECTOR",
    "Prepare immutable release evidence for an owner-operated deployment outside this controller.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-OPERATIONS",
    "Operations Specialist",
    "ROLE-TECH-DIRECTOR",
    "Analyze health, recovery, rollback, and incident evidence without speculative production edits.",
    "route-critical-review",
  ),
  specialist(
    "ROLE-EXPERIMENTER",
    "Sandbox Experimenter",
    "ROLE-IMPROVEMENT-DIRECTOR",
    "Run bounded local experiments against approved hypotheses.",
    "route-complex-specialist",
    "isolated",
  ),
  verifier(
    "ROLE-EVALUATOR",
    "Improvement Evaluator",
    "Compare baseline and candidate outcomes independently.",
    "route-critical-review",
    ["ROLE-EXPERIMENTER", "ROLE-IMPROVEMENT-DIRECTOR"],
  ),
];

export const ROLE_CONTRACTS: Readonly<Record<string, RoleContract>> = Object.fromEntries(
  roleContracts.map((contract) => [contract.roleId, contract]),
);

export interface AgentTemplate {
  agentId: string;
  displayName: string;
  roleId: string;
  parentAgentId: string | null;
  temporary?: boolean;
}

const BASE_AGENT_TEMPLATES: readonly AgentTemplate[] = [
  { agentId: "OWNER-01", displayName: "Owner", roleId: "ROLE-OWNER", parentAgentId: null },
  {
    agentId: "ORCH-01",
    displayName: "Chief Orchestrator",
    roleId: "ROLE-ORCHESTRATOR",
    parentAgentId: "OWNER-01",
  },
  {
    agentId: "DIR-COMMS",
    displayName: "Communications Director",
    roleId: "ROLE-COMMS-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-BILLING",
    displayName: "Billing Director",
    roleId: "ROLE-BILLING-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-LEGAL",
    displayName: "Legal Operations Director",
    roleId: "ROLE-LEGAL-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-PRODUCT",
    displayName: "Product Director",
    roleId: "ROLE-PRODUCT-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-TECH",
    displayName: "Technology Director",
    roleId: "ROLE-TECH-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-SECURITY",
    displayName: "Security Director",
    roleId: "ROLE-SECURITY-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-QUALITY",
    displayName: "Quality Director",
    roleId: "ROLE-QUALITY-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "DIR-IMPROVE",
    displayName: "Improvement Director",
    roleId: "ROLE-IMPROVEMENT-DIRECTOR",
    parentAgentId: "ORCH-01",
  },
  {
    agentId: "AGT-TRIAGE",
    displayName: "Triage & Routing",
    roleId: "ROLE-TRIAGE",
    parentAgentId: "DIR-COMMS",
  },
  {
    agentId: "AGT-COMMS",
    displayName: "General Communications",
    roleId: "ROLE-GENERAL-COMMS",
    parentAgentId: "DIR-COMMS",
  },
  {
    agentId: "AGT-CONTACT",
    displayName: "Contact & Follow-up",
    roleId: "ROLE-CONTACT",
    parentAgentId: "DIR-COMMS",
  },
  {
    agentId: "AGT-SCHEDULE",
    displayName: "Scheduling",
    roleId: "ROLE-SCHEDULING",
    parentAgentId: "DIR-COMMS",
  },
  {
    agentId: "AGT-COMPLAINTS",
    displayName: "Complaints & Escalation",
    roleId: "ROLE-COMPLAINTS",
    parentAgentId: "DIR-COMMS",
  },
  { agentId: "AGT-INVOICE", displayName: "Invoice", roleId: "ROLE-INVOICE", parentAgentId: "DIR-BILLING" },
  {
    agentId: "AGT-PAYMENT",
    displayName: "Payment Tracking",
    roleId: "ROLE-PAYMENT",
    parentAgentId: "DIR-BILLING",
  },
  {
    agentId: "AGT-RECON",
    displayName: "Reconciliation",
    roleId: "ROLE-RECONCILIATION",
    parentAgentId: "DIR-BILLING",
  },
  {
    agentId: "AGT-COLLECTIONS",
    displayName: "Collections",
    roleId: "ROLE-COLLECTIONS",
    parentAgentId: "DIR-BILLING",
  },
  {
    agentId: "AGT-ADJUSTMENTS",
    displayName: "Adjustments & Disputes",
    roleId: "ROLE-ADJUSTMENTS",
    parentAgentId: "DIR-BILLING",
  },
  {
    agentId: "AGT-PAYABLES",
    displayName: "Payables & Reporting",
    roleId: "ROLE-PAYABLES",
    parentAgentId: "DIR-BILLING",
  },
  {
    agentId: "AGT-LEGAL-INTAKE",
    displayName: "Legal Intake",
    roleId: "ROLE-LEGAL-INTAKE",
    parentAgentId: "DIR-LEGAL",
  },
  {
    agentId: "AGT-CONTRACTS",
    displayName: "Contracts",
    roleId: "ROLE-CONTRACTS",
    parentAgentId: "DIR-LEGAL",
  },
  {
    agentId: "AGT-COMPLIANCE",
    displayName: "Compliance & Privacy",
    roleId: "ROLE-COMPLIANCE",
    parentAgentId: "DIR-LEGAL",
  },
  { agentId: "AGT-IP", displayName: "Corporate & IP", roleId: "ROLE-IP", parentAgentId: "DIR-LEGAL" },
  {
    agentId: "AGT-COUNSEL",
    displayName: "Disputes & Counsel",
    roleId: "ROLE-COUNSEL",
    parentAgentId: "DIR-LEGAL",
  },
  { agentId: "AGT-DESIGN", displayName: "Product & UX", roleId: "ROLE-DESIGN", parentAgentId: "DIR-PRODUCT" },
  { agentId: "AGT-BACKEND", displayName: "Backend", roleId: "ROLE-BACKEND", parentAgentId: "DIR-TECH" },
  { agentId: "AGT-WEB", displayName: "Frontend", roleId: "ROLE-WEB", parentAgentId: "DIR-TECH" },
  { agentId: "AGT-MOBILE", displayName: "Mobile", roleId: "ROLE-MOBILE", parentAgentId: "DIR-TECH" },
  {
    agentId: "AGT-INTEGRATIONS",
    displayName: "Integrations",
    roleId: "ROLE-INTEGRATIONS",
    parentAgentId: "DIR-TECH",
  },
  { agentId: "AGT-VOICE", displayName: "Voice", roleId: "ROLE-VOICE", parentAgentId: "DIR-TECH" },
  { agentId: "AGT-DEPLOY", displayName: "Deployment", roleId: "ROLE-DEPLOYMENT", parentAgentId: "DIR-TECH" },
  { agentId: "AGT-OPS", displayName: "Operations", roleId: "ROLE-OPERATIONS", parentAgentId: "DIR-TECH" },
  {
    agentId: "AGT-EXPERIMENT",
    displayName: "Sandbox Experimenter",
    roleId: "ROLE-EXPERIMENTER",
    parentAgentId: "DIR-IMPROVE",
  },
  {
    agentId: "AGT-EVALUATOR",
    displayName: "Improvement Evaluator",
    roleId: "ROLE-EVALUATOR",
    parentAgentId: "ORCH-01",
  },
] as const;

export function buildAgentTemplates(ownerDisplayName = "Owner"): readonly AgentTemplate[] {
  const ownerName = ownerDisplayName.trim();
  if (ownerName.length < 1 || ownerName.length > 80) {
    throw new Error("Owner display name must contain 1-80 characters");
  }
  return BASE_AGENT_TEMPLATES.map((template) =>
    template.agentId === "OWNER-01" ? { ...template, displayName: ownerName } : { ...template },
  );
}

export const AGENT_TEMPLATES: readonly AgentTemplate[] = buildAgentTemplates();

export function getRoleContract(roleId: string): RoleContract {
  const contract = ROLE_CONTRACTS[roleId];
  if (!contract) {
    throw new Error(`Unknown role contract: ${roleId}`);
  }
  return contract;
}
